Be more careful about blindly continuing regardless.

diff --git a/lib/chef/knife/bootstrap/ubuntu11.10-cluster_chef.erb b/lib/chef/knife/bootstrap/ubuntu11.10-cluster_chef.erb
--- a/lib/chef/knife/bootstrap/ubuntu11.10-cluster_chef.erb
+++ b/lib/chef/knife/bootstrap/ubuntu11.10-cluster_chef.erb
@@ -7,9 +7,12 @@ bash -c '
 # * pushes the node identity into the first-boot.json
 # * installs the chef-client service and kicks off the first run of chef
 
+set -e
+
 <%= (@config[:verbosity].to_i > 1 ? 'set -v' : '') %>
 
-mkdir -p /tmp/knife-bootstrap ; chmod 700 /tmp/knife-bootstrap 
+mkdir -p /tmp/knife-bootstrap
+chmod 700 /tmp/knife-bootstrap 
 cd /tmp/knife-bootstrap
 
 <%= "export http_proxy=\"#{knife_config[:bootstrap_proxy]}\"" if knife_config[:bootstrap_proxy] -%>
@@ -85,7 +88,7 @@ EOP
 ) > /etc/chef/first-boot.json
 
 echo -e "`date` \n\n**** \n**** Adding chef client runit scripts:\n****\n"
-service chef-client stop >/dev/null 2>&1 ; sleep 1 ; killall chef-client 2>/dev/null ; true
+(service chef-client stop >/dev/null 2>&1 ; sleep 1 ; killall chef-client 2>/dev/null) || true
 mkdir -p /var/log/chef /var/chef /etc/service /etc/sv/chef-client/{log/main,supervise} 
 cat > /etc/sv/chef-client/log/run <<EOF
 #!/bin/bash
@@ -99,7 +102,7 @@ EOF
 chmod +x  /etc/sv/chef-client/log/run /etc/sv/chef-client/run
 ln -nfs /usr/bin/sv /etc/init.d/chef-client
 
-service chef-client stop ; true
+service chef-client stop || true
 
 <%- if (@config[:bootstrap_runs_chef_client].to_s == 'true') || (@chef_config.knife[:bootstrap_runs_chef_client].to_s == 'true') %>
 echo -e "`date` \n\n**** \n**** First run of chef:\n****\n"
@@ -116,4 +119,4 @@ ln -nfs /etc/sv/chef-client /etc/service/chef-client
 service chef-client start
 
 echo -e "`date` \n\n**** \n**** Cluster Chef client bootstrap complete\n****\n"
-'
+' || echo "Chef bootstrap failed!"
